pipeline:
  main:
    image: alpine:edge
    environment:
      # Fail build if there are warnings
      - RUSTFLAGS=-D warnings
    commands:
      # Get packages needed for building
      - >-
         apk -U add
         rust cargo gnupg gettext file make automake autoconf protobuf bash
      # Install rust-fmt for checking if code is formatted correctly
      - cargo install rustfmt && export PATH=$PATH:/root/.cargo/bin
      # Check that there is no formatting to be done by `cargo fmt`
      - '[ -z $("cargo fmt -- --write-mode diff") ]'
      # Check that we can build and test all configurations
      - ./resources/build-configurations.sh
      # TODO: Run python end-to-end tests

