pipeline:
  main:
    image: alpine:edge
    commands:
      # Install prerequisites.
      - apk add --update-cache
      - apk add gettext file make automake autoconf pkgconfig curl nettle-dev clang-dev gmp-dev
      - apk add protobuf bash gnupg
      - apk add cargo python3
      - curl -sSf https://sh.rustup.rs | sh -s -- -y
      # Check rust code compiles without warnings.
      - RUSTFLAGS='-D warnings' cargo check --all --tests
      # Check rust code compiles with different features.
      - cargo check --no-default-features --features "use-graph use-protobuf use-tcp use-unix-socket"
      - cargo check --no-default-features --features "use-protobuf use-tcp use-unix-socket use-black-hole"
      - cargo check --no-default-features --features "use-protobuf use-tcp use-unix-socket use-random-response"
      # Check rust code passes unit tests.
      - cargo test
      # Check rust code is formatted correctly.
      - cargo fmt -- --check
      # TODO: Enable clippy checks after fixing all issues.
      # TODO: Run python end-to-end tests.
