pipeline:
  main:
    image: alpine:edge
    environment:
      # Fail build if there are warnings
      - RUSTFLAGS=-D warnings
    commands:
      # Get packages needed for building
      - >-
         apk -U add
         rust cargo gnupg gettext file make automake autoconf protobuf bash
         python3
      # TODO: Check code is formatted correctly. This requires a nightly rust
      # tool chain, which is not available in alpine currently.
      # Check that we can build and test all configurations
      - ./resources/build-configurations.py
      # TODO: Run python end-to-end tests

